# Setup
title:               Tech
tagline:             
description:         
url:                 https://tech.dedunu.info
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Dedunu Dhananjaya
  url:               https://dedunu.info
  email:             hello@dedunu.info

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
