# Setup
title:               Tech | Dedunu
tagline:             
description:         
url:                 https://dedunu.github.io/tech
baseurl:             ''
paginate:            1
permalink:           pretty

# About/contact
author:
  name:              Dedunu Dhananjaya
  url:               https://dedunu.info
  email:             hello@dedunu.info

# Gems
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate

# Custom vars
version:             1.1.0
